name: Create YAAM environment

description: Create environment to test and build YAAM

on:
  workflow_call:

outputs:
  git-latest-tag:
    description: "Latest git-branch tag"
    value: ${{ steps.latest.outputs.tag }}
  git-latest-rev:
    description: "Latest git-branch revision"
    value: ${{ steps.latest.outputs.rev }}
  git-tag-rev:
    description: "Latest tag git-branch revision"
    value: ${{ steps.tag.outputs.rev }}
  python-version:
    description: "Python version"
    value: ${{ steps.python.outputs.version }}
  python-path:
    description: "Python path"
    value: ${{ steps.python.outputs.pythonpath }}

jobs:
  using: composite

  create-env:

    steps:

      - name: Get last available repo info
        id: latest
        run: |
          echo "::set-output name=tag::$(git describe --tags --abbrev=0 --always)"
          echo "::set-output name=rev::$(git rev-parse --short=8 head)"
        
      - name: Get tag revision
        id: tag
        run: |
          echo "::set-output name=rev::$(@(git rev-list -n 1 ${{ steps.latest.outputs.tag }}).substring(0, 8))"

      - name: Initialize MSVC developer tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: "x64"
          toolset: "14.*"
          
      - name: Set up Python distribution
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.9"
          architecture: "x64"
          cache: pip
          
      - name: Get Python distribution info
        id: python
        shell: pwsh
        run: |
          echo "::set-output name=version::$(@(python -V).substring(7))"
          echo "::set-output name=python-path::$(@(./scripts/find-pythonpath.ps1))"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          python ${{ steps.python.outputs.python-path }}/Scripts/pywin32_postinstall.py -install
        