name: Lint, Test & Build YAAM

description: Release the built artifacts

on:
  workflow_call:

inputs:
  git-tag:
    description: "Latest git branch tag"
    required: true
    default: "0.0.0"
  
  git-rev:
    description: "Latest git branch revision"
    required: true
    default: "0"
  
  is-pre-release:
    description: "Flag this release as a pre-release"
    required: false
    default: false

  is-draft:
    description: "Flag this release as a draft release"
    required: false
    default: false

jobs:
  using: composite

  release-artifacts:

    steps:
      - name: Create string version
        id: version
        shell: pwsh
        run: |
          echo "::set-output name=short::$(@(./scripts/get-version.ps1 -tag ${{ inputs.git-tag }} -short))"
          echo "::set-output name=complete::$(@(./scripts/get-version.ps1 -tag ${{ inputs.git-tag }}  -revision ${{ inputs.git-rev }} -complete))"

      - name: Upload artifacts
        id: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: yaam-standalone-msvc-${{ inputs.git-tag }}
          path: ${{ github.workspace }}/artifacts/yaam-standalone-msvc-${{ inputs.git-tag }}.zip
          retention-days: 7
      
      - name: Test release changelog existence
        id: changelog-info
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ github.workspace }}/changelogs/v${{ steps.version.outputs.short }}.md

      - name: Create release changelog
        if: ${{ steps.changelog-info.outputs.file_exists == 'false' }}
        id: automated-changelog
        shell: pwsh
        run: |
          echo "Automated build release" >> ${{ github.workspace }}/changelogs/v${{ steps.version.outputs.short }}.md

      - name: Release built artifacts
        id: release
        uses: ncipollo/release-action@v1
        with:
          name: YAAM release ${{ inputs.git-tag }}
          tag: ${{ inputs.git-tag }}
          bodyFile: ${{ github.workspace }}/changelogs/v${{ steps.version.outputs.short }}.md
          artifacts: ${{ github.workspace }}/artifacts/yaam-standalone-msvc-${{ inputs.git-tag }}.zip
          token: ${{ secrets.yaam_publish_token }}
          prerelease: ${{ inputs.is-pre-release }}
          draft: ${{ inputs.is-draft }} 
          allowUpdates: true
          # removeArtifacts: true
          replacesArtifacts: true
