# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish YAAM

on:

  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag'
        required: false 
        type: string
      name:
        description: 'Release name'
        required: true
        type: string
      body:
        description: 'Release body'
        required: true
        type: string
#   push:
#     # Sequence of patterns matched against refs/tags
#     tags:
#     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        pytest
        
    - name: Build with nuitka
      shell: pwsh
      run: |
        .\nuitka-make.ps1
        
    - name: Zip built artifacts for upload
      run: zip yaam-standalone-msvc.zip ./bin/standalone/mvsc/yaam/* -r
      
#     - name: Archive production artifacts
#       uses: actions/upload-artifact@v2
#       with:
#         name: yaam-standalone-msvc
#         path: |
#           bin/standalone/mvsc/yaam/yaam-standalone-msvc.zip
          
    - name: Release built artifacts
      uses: ncipollo/release-action@v1
      with:
        name: YAAM release ${{github.ref_name}}
        body: Automated release for YAAM ${{github.ref_name}}
        artifacts: bin/standalone/mvsc/yaam/yaam-standalone-msvc-${{github.ref_name}}.zip
        token: ${{ secrets.RELEASE_TOKEN }}
        
    
